spring:
  application:
    name: ms-notificacoes
  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 465
    username: coloque seu email
    password: coloque sua senha
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_SERVER}:${KEYCLOAK_PORT}/realms/bookexchangerealm
          jwk-set-uri: http://${KEYCLOAK_SERVER}:${KEYCLOAK_PORT}/realms/bookexchangerealm/protocol/openid-connect/certs

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value} }
  client:
    service-url:
      defaultZone: http://book-exchange-user:rnege-aoxsu-chokbe@${EUREKA_SERVER}:8761/eureka

mq:
  queues:
    envio-notificacoes: envio-notificacoes