spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      #default-filters:
       # - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bookexchangerealm
          jwk-set-uri: http://localhost:8081/realms/bookexchangerealm/protocol/openid-connect/certs

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://book-exchange-user:rnege-aoxsu-chokbe@localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: INFO