spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: book-exchange-user
      password: rnege-aoxsu-chokbe

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka


